:doctitle: Title
:author: Jerod Gawne
:email: jerodg@pm.me
:docdate: 04 January 2024
:revdate: {docdatetime}
:doctype: article
:sectanchors:
:sectlinks:
:sectnums:
:toc:
:icons: font
:keywords: problem, python

== Problem
[.lead]
The built-in sort doesn't take into account numbers with more than one digit.

[source,lang-py,s-code-block]
----
['Elm11', 'Elm12', 'Elm2', 'elm0', 'elm1', 'elm10', 'elm13', 'elm9']
----

For instance, you are looking for something like this:

[source,lang-py,s-code-block]
----
['elm0', 'elm1', 'Elm2', 'elm9', 'elm10', 'Elm11', 'Elm12', 'elm13']
----

This way elm0 comes before elm10.

=== Use-Cases
Naturally sorting a list is a common operation in various fields of computer science and data management.
Here are some use cases:

1. **File Management**: In file management, you might have a list of file names and you want to sort them in a way that aligns with human expectations (i.e., 'file1' comes before 'file10').

2. **Data Analysis**: In data analysis, you might have a list of data points with alphanumeric identifiers, and you want to sort them naturally for better readability and understanding.

3. **User Interface Design**: In user interface design, you might have a list of items (like product names, usernames, etc.) that you want to display in a naturally sorted order to improve the user experience.

4. **Database Operations**: In database operations, you might have a list of records with alphanumeric identifiers, and you want to sort them naturally for better data management and querying.

5. **Text Processing**: In text processing, you might have a list of words or sentences that you want to sort naturally for linguistic analysis or natural language processing tasks.

These are just a few examples.
The concept of naturally sorting a list can be applied in many other scenarios depending on the problem at hand.
=== Constraints == Examples === Example 0 == Follow-up == Related Topics
