:doctitle: Merge Sorted Arrays Problem
:author: Jerod Gawne
:email: jerodg@pm.me
:docdate: 04 January 2024
:revdate: {docdatetime}
:doctype: article
:sectanchors:
:sectlinks:
:sectnums:
:toc:
:icons: font
:imagesdir: ./img
:keywords: problem, python

== Problem

[.lead]
You are given two integer arrays `+nums1+` and `+nums2+`, sorted in *non-decreasing order*, and two integers `+m+` and `+n+`, representing the number of elements in `+nums1+` and `+nums2+` respectively.

*Merge* `+nums1+` and `+nums2+` into a single array sorted in *non-decreasing order*.

The final sorted array should not be returned by the function, but instead be _stored inside the array _`+nums1+`. To accommodate this, `+nums1+` has a length of `+m + n+`, where the first `+m+` elements denote the elements that should be merged, and the last `+n+` elements are set to `+0+` and should be ignored. `+nums2+` has a length of `+n+`.

=== Constraint(s)

* `+nums1.length == m + n+`
* `+nums2.length == n+`
* `+0 <= m, n <= 200+`
* `+1 <= m + n <= 200+`
* `+-10+`^`+9+`^`+ <= nums1[i], nums2[j] <= 10+`^`+9+`^

=== Example(s)

==== 0

.Input
[source,python,linenums]
----
[1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3
----

.Output
[source,python,linenums]
----
[1,2,2,3,5,6]
----

Explanation: The arrays we are merging are [1,2,3] and [2,5,6].
The result of the merge is [1,2,2,3,5,6] with the underlined elements coming from nums1.

==== 1

.Input
[source,python,linenums]
----
nums1 = [1], m = 1, nums2 = [], n = 0
----

.Output
[source,python,linenums]
----
[1]
----

Explanation: The arrays we are merging are [1] and [].
The result of the merge is [1].

==== 2

.Input
[source,python,linenums]
----
nums1 = [0], m = 0, nums2 = [1], n = 1
----

.Output
[source,python,linenums]
----
[1]
----

Explanation: The arrays we are merging are [] and [1].
The result of the merge is [1].
NOTE: that because m = 0, there are no elements in nums1. The 0 is only there to ensure the merge result can fit in nums1.

==== 3

.Input
[source,python,linenums]
----

----

.Output
[source,python,linenums]
----

----

==== 4

.Input
[source,python,linenums]
----

----

.Output
[source,python,linenums]
----

----

== Use-Case(s)

== Common Mistakes

== Best Practices

== Test Strategies

== Performance Optimization

== Follow-up

Can you come up with an algorithm that runs in `+O(m + n)+` time?

== Related Topics

== References
